export const eleComponents = [
    //   ["Row", "Row 行"],
    //   ["Col", "Col 列"],
    // ["Container", "Container 布局容器"],
    // ["Icon", "Icon 图标"],
    ["Button", "Button 按钮"],
    ["Link", "Link 文字链接"],
    // ["Space", "Space 间距"],
    // ["Scrollbar", "Scrollbar 滚动条"],
    ["Radio", "Radio 单选框"],
    ["Checkbox", "Checkbox 多选框"],
    // ["InputNumber", "InputNumber 计数器"],
    // ["Select", "Select 选择器"],
    // ["Cascader", "Cascader 级联选择器"],
    // ["Slider", "Slider 滑块"],
    // ["TimePicker", "TimePicker 时间选择器"],
    // ["TimeSelect", "TimeSelect 时间选择"],
    // ["DatePicker", "DatePicker 日期选择器"],
    // ["DateTimePicker", "DateTimePicker 日期时间选择器"],
    // ["Upload", "Upload 上传"],
    // ["Rate", "Rate 评分"],
    // ["ColorPicker", "ColorPicker 颜色选择器"],
    // ["Transfer", "Transfer 穿梭框"],
    // ["Form", "Form 表单"],
    // ["Table", "Table 表格"],
    // ["Tag", "Tag 标签"],
    // ["Progress", "Progress 进度条"],
    // ["Tree", "Tree 树形控件"],
    // ["Pagination", "Pagination 分页"],
    // ["Avatar", "Avatar 头像"],
    // ["Skeleton", "Skeleton 骨架屏"],
    // ["Empty", "Empty 空状态"],
    // ["Descriptions", "Descriptions 描述列表"],
    // ["Result", "Result 结果"],
    // ["Alert", "Alert 警告"],
    // ["Loading", "Loading 加载"],
    ["Message", "Message 消息提示"],
    // ["MessageBox", "MessageBox 弹框"],
    // ["Notification", "Notification 通知"],
    // ["Affix", "Affix 固钉"],
    // ["NavMenu", "NavMenu 导航菜单"],
    // ["Tabs", "Tabs 标签页"],
    // ["Breadcrumb", "Breadcrumb 面包屑"],
    // ["PageHeader", "PageHeader 页头"],
    // ["Dropdown", "Dropdown 下拉菜单"],
    // ["Steps", "Steps 步骤条"],
    // ["Dialog", "Dialog 对话框"],
    // ["Tooltip", "Tooltip 文字提示"],
    // ["Popover", "Popover 弹出框"],
    // ["Popconfirm", "Popconfirm 气泡确认框"],
    // ["Card", "Card 卡片"],
    ["Carousel", "Carousel 走马灯"],
    // ["Collapse", "Collapse 折叠面板"],
    // ["Timeline", "Timeline 时间线"],
    // ["Divider", "Divider 分割线"],
    // ["Calendar", "Calendar 日历"],
    // ["Image", "Image 图片"],
    // ["Backtop", "Backtop 回到顶部"],
    // ["InfiniteScroll", "InfiniteScroll 无限滚动"],
    // ["Drawer", "Drawer 抽屉"],
];
